language: python
python: 2.7
env:
  - TOXENV=py26-django14
  - TOXENV=py26-django16
  - TOXENV=py27-django14
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py34-django17
  - TOXENV=py27-django18
  - TOXENV=py34-django18
  - TOXENV=docs
  - TOXENV=pep8
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
