language: python
env:
  - DJANGO=1.4
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=master
matrix:
  include:
    - python: 2.6
      env: DJANGO=1.4 TOXENV=py26-django14
    - python: 2.6
      env: DJANGO=1.6 TOXENV=py26-django16
    - python: 2.7
      env: DJANGO=1.4 TOXENV=py27-django14
    - python: 2.7
      env: DJANGO=1.6 TOXENV=py27-django16
    - python: 2.7
      env: DJANGO=1.7 TOXENV=py27-django17
    - python: 3.4
      env: DJANGO=1.7 TOXENV=py34-django17
    - python: 2.7
      env: DJANGO=1.8 TOXENV=py27-django18
    - python: 3.4
      env: DJANGO=1.8 TOXENV=py34-django18
    - python: 2.7
      env: DJANGO=1.9 TOXENV=py27-django19
    - python: 3.4
      env: DJANGO=1.9 TOXENV=py34-django19
    - python: 2.7
      env: DJANGO=1.10 TOXENV=py27-django110
    - python: 3.4
      env: DJANGO=1.10 TOXENV=py34-django110
    - python: 2.7
      env: DJANGO=1.11 TOXENV=py27-django111
    - python: 3.4
      env: DJANGO=1.11 TOXENV=py34-django111
    - python: 2.7 
      env: DJANGO=1.11 TOXENV=docs
    - python: 2.7 
      env: DJANGO=1.11 TOXENV=pep8

install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
